# P[1]: Bellman equation, 4x4 grid world

In [1]:
import numpy as np

# initializing
old_value = np.zeros((4,4))
new_value = np.zeros((4,4)) 
policy = {'up':0.25,'down':0.25,'left':0.25,'right':0.25}

In [2]:
print('old_value',old_value)
print('new_value',new_value)
print('policy',policy)

old_value [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
new_value [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
policy {'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}


In [3]:
for key,value in policy.items():
    print(key,value)

up 0.25
down 0.25
left 0.25
right 0.25


In [4]:
# 1st step
dummy_list = []
for key,value in policy.items():
    dummy_list.append((-1+old_value)*value)
dummy_list = np.sum(np.array(dummy_list),axis=0)
new_value = dummy_list
new_value[0,0],new_value[-1,-1] = 0,0
old_value = new_value

In [5]:
print(new_value[1:,:])

[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]


In [6]:
# 2nd step
dummy_list = []
mid_term = np.zeros((4,4))
for key,value in policy.items():
    # upper bound
    if key == 'up':
        mid_term[1:,:] += (-1+old_value[:-1,:])*value
        mid_term[0,:] += (-1+old_value[0,:])*value
    # down bound
    elif key == 'down':
        mid_term[:-1,:] += (-1+old_value[1:,:])*value
        mid_term[-1,:] += (-1+old_value[-1,:])*value
    # left bound
    elif key == 'left':
        mid_term[:,1:] += (-1+old_value[:,:-1])*value
        mid_term[:,0] += (-1+old_value[:,0])*value
    # right bound
    else:
        mid_term[:,:-1] += (-1+old_value[:,1:])*value
        mid_term[:,-1] += (-1+old_value[:,-1])*value
    dummy_list.append(mid_term)
dummy_list = np.mean(np.array(dummy_list),axis=0)
new_value = dummy_list
new_value[0,0],new_value[-1,-1] = 0,0
old_value = new_value

In [7]:
print(new_value)

[[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]


In [8]:
# Iteration
for it in range(100):
    dummy_list = []
    mid_term = np.zeros((4,4))
    for key,value in policy.items():
        # upper bound
        if key == 'up':
            mid_term[1:,:] += (-1+old_value[:-1,:])*value
            mid_term[0,:] += (-1+old_value[0,:])*value
        # down bound
        elif key == 'down':
            mid_term[:-1,:] += (-1+old_value[1:,:])*value
            mid_term[-1,:] += (-1+old_value[-1,:])*value
        # left bound
        elif key == 'left':
            mid_term[:,1:] += (-1+old_value[:,:-1])*value
            mid_term[:,0] += (-1+old_value[:,0])*value
        # right bound
        else:
            mid_term[:,:-1] += (-1+old_value[:,1:])*value
            mid_term[:,-1] += (-1+old_value[:,-1])*value
        dummy_list.append(mid_term)
    dummy_list = np.mean(np.array(dummy_list),axis=0)
    new_value = dummy_list
    new_value[0,0],new_value[-1,-1] = 0,0
    old_value = new_value
print(new_value)

[[  0.         -13.94854904 -19.92375894 -21.91468175]
 [-13.94854904 -17.93283614 -19.92426894 -19.92375894]
 [-19.92375894 -19.92426894 -17.93283614 -13.94854904]
 [-21.91468175 -19.92375894 -13.94854904   0.        ]]


# P[2]: Bellman optimality equation, 4x4 grid world

In [9]:
# initializing
old_value = np.zeros((4,4))
new_value = np.zeros((4,4)) 

In [10]:
# 1st step
new_value = -1+old_value
new_value[0,0]=0
old_value = new_value

In [11]:
print(new_value)

[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]


In [12]:
# 2nd step -> k_번 iteration
for k in range(7):
    for row in range(4):
        for col in range(4):
            # top-left corner -> always zero
            if row == 0 and col == 0:
                pass
            # top-mid   
            elif row == 0 and col != 3:
                new_value[row][col] = max((-1+old_value[row][col-1]),(-1+old_value[row+1][col]),(-1+old_value[row][col+1]),(-1+new_value[row][col]))
            # top-right corner 
            elif row == 0 and col == 3:
                new_value[row][col] = max((-1+old_value[row][col-1]),(-1+old_value[row+1][col]),(-1+new_value[row][col]))
            # left-mid
            elif col == 0 and row != 3:
                new_value[row][col] = max((-1+old_value[row+1][col]),(-1+old_value[row][col+1]),(-1+old_value[row-1][col]))
            # left-bottom corner
            elif col == 0 and row == 3:
                new_value[row][col] = max((-1+old_value[row-1][col]),(-1+old_value[row][col+1]),(-1+new_value[row][col]))
            # bottom-mid
            elif row == 3 and col != 3:
                new_value[row][col] = max((-1+old_value[row-1][col]),(-1+old_value[row][col-1]),(-1+old_value[row][col+1]),(-1+new_value[row][col]))
            # bottom-right corner
            elif row == 3 and col == 3:
                new_value[row][col] = max((-1+old_value[row-1][col]),(-1+old_value[row][col-1]),(-1+new_value[row][col]))
            # right-mid
            elif col == 3 and row != 3:
                new_value[row][col] = max((-1+old_value[row-1][col]),(-1+old_value[row][col-1]),(-1+old_value[row+1][col]),(-1+new_value[row][col]))
            # else
            else:
                new_value[row][col] = max((-1+old_value[row-1][col]),(-1+old_value[row][col-1]),(-1+old_value[row+1][col]),(-1+old_value[row][col+1]))
    old_value = new_value        

In [13]:
print(new_value)

[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4. -5.]
 [-3. -4. -5. -6.]]
